#!/bin/bash

# remove this line if you want to disable using the clipboard
CLIPBOARD=true


PLATFORM=`uname`
function _clip(){
  if [[ $CLIPBOARD ]]; then
    if [[ "$PLATFORM" == "Darwin" ]]; then
      echo $1 | pbcopy
    elif [[ "$PLATFORM" == "Linux" ]]; then
      echo $1 | xclip -sel clipboard
    fi
  fi
}

function _myip(){
  ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | head -n1
}

FILES=()
PORT=9054


while [ ! $# -eq 0 ]
do
    case "$1" in
        -c)
            CLEAR=1;
            ;;
        .)
            FILES+=("`pwd`")
            ;;
        *)
            FILES+=("$1");
            ;;
    esac
    shift
done

function serveFile(){
  local FILE=$1

  if [[ "$FILE" ]]; then
    FULLPATH=`readlink -f $FILE`
    FILE=`basename $FILE`
  
    if [ -f "$FULLPATH" ] || [ -d "$FULLPATH" ]; then
      ln -snfF $FULLPATH ~/.pythonserver/$FILE
    fi
  fi
}

if [ ! -d ~/.pythonserver ];then
  mkdir ~/.pythonserver
fi

if [ $CLEAR ]; then
  echo Clearing out..
  rm -f ~/.pythonserver/*
fi

for f in "${FILES[@]}"; do
  serveFile "$f"
done


BASE="http://$(_myip):$PORT" 
SINGLEFILE=`basename "${FILES[0]}"`

if [[ "$SINGLEFILE" ]]; then
  _clip "$BASE/$SINGLEFILE"
else
  _clip "$BASE"
fi

if [ ! `pgrep -f "python -m SimpleHTTPServer $PORT"` ]; then
  python -m SimpleHTTPServer $PORT &> /dev/null &
  echo Started new server on $BASE
elif [ ${#FILES[@]} -eq 1 ]; then
  echo Rehosted: "$BASE/$SINGLEFILE"
elif [ "$SINGLEFILE" ]; then
  echo Rehosted: $BASE
fi

